# Generated by Django 5.1.1 on 2024-09-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_stars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stars',
            new_name='Star',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='stars',
            new_name='star',
        ),
    ]
