# Generated by Django 5.1.1 on 2024-09-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_stars_star_rename_stars_star_star'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Star',
        ),
    ]
