# Generated by Django 5.1.1 on 2024-09-13 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_delete_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(verbose_name='Stars')),
                ('rating', models.TextField(max_length=250)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.restaurant')),
            ],
        ),
    ]
