# Generated by Django 5.1.1 on 2024-09-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='star',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1, verbose_name='Stars'),
        ),
    ]
